fail_fast: true
default_stages: [commit]
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.7.0
    hooks:
      - id: isort
        name: isort (python)
      - id: isort
        name: isort (cython)
        types: [cython]
      - id: isort
        name: isort (pyi)
        types: [pyi]
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.0
    hooks:
      - id: flake8
        additional_dependencies: ["flake8-absolute-import"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
  - repo: local
    hooks:
      - id: typerdocs
        name: Make typer docs
        language: system
        pass_filenames: false
        always_run: true
        entry: poetry run typer pyrepositoryminer utils docs --name pyrepositoryminer --output DOCS.md
