name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependecies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install -d
      - name: pre-commit hooks
        uses: pre-commit/action@v2.0.0
      - name: Test
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run test
